apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tom
  description: tom test component
  annotations:
    datadoghq.com/site: https://app.datadoghq.com
    
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  dependsOn:
    - resource:default/artists-db
  providesApis:
    - tom_prod
    - tom_dev
