apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tom
  description: tom test component
  annotations:
    datadoghq.com/site: https://app.datadoghq.com/dash/integration/30322/kubernetes-pods-overview?from_ts=1679997263331&to_ts=1680000863331&live=true
    
spec:
  type: service
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  dependsOn:
    - resource:default/artists-db
